### PR TITLE
Provision SSHPublicKey while use custom SSH Private key

### LINKED ISSUE #100: Setup SSHPublicKey value while use custom SSHPrivateKeyFile
#### Description

Currently, [the code](https://github.com/hashicorp/packer-plugin-sdk/blob/622cc94659d8e673b0c1eae07b68c4e95c3b66be/communicator/step_ssh_keygen.go#L34), when using a user-specified SSH private key file, leaves the `SSHPublicKey` field explicitly empty. 
On the other hand when use  generated keypair value of SSHPublicKey [provisioned](https://github.com/hashicorp/packer-plugin-sdk/blob/622cc94659d8e673b0c1eae07b68c4e95c3b66be/communicator/step_ssh_keygen.go#L60).

#### Use Case(s)

Builder could use value of `SSHPublicKey` to correct provision instance when use custom private SSH key file.

### PR DESCRIPTION
**Pull request by GennadySpb**
Closes #100

### CODE REVIEW

**Comment by GennadySpb** [comment]
Hi @nywilken ! 
Please take a look at this PR :)

**Comment by nywilken** [comment]
Hi @GennadySpb this change looks good to me. I just want to figure out if we need some documentation to denote this behavior.

**Review by nywilken — APPROVED** [review]
@GennadySpb thanks for this enhancement. The change does make sense to have as part of the SDK. Please not that builders will not automatically upload the generated PubKey, as the majority of the builders are set to not set any SSH public keys settings when a private key is specified. 

If you have a particular builder that you plan to use this feature with you will need to open a separate PR for it on its respective repository.

**Comment by GennadySpb** [comment]
Thank you @nywilken ! I will keep it in mind.

**Pull request merged**
