### PR TITLE
communicator: fix SSH config typo

### PR DESCRIPTION
**Pull request by lbajolet-hashicorp**
Fix small typo in the comment for an SSH configuration option where algorithm was misspelled.

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
LGTM

**Comment by nywilken** [comment]
Oh this is a shared partial that needs to be re-generated before merging.

**Comment by lbajolet-hashicorp** [comment]
Yes, the tests do point it out; I've amended this commit, if tests succeed, I'll merge this PR, thanks for the review!

**Comment by nywilken** [comment]
You linter is out of date. I pushed a fixed to main a few days ago. Can you please pull down the latest main and rebase.

**Comment by lbajolet-hashicorp** [comment]
Hmmm, that's weird, I have fetched and rebased on top of main as it stands. Is there anything else I should be doing for the linter to be up-to-date? I basically ran `make generate` in order to generate the latest version of the partials, is it as expected?

**Pull request merged**
